// GENERATED by tools/gen.mjs. Do not edit.
// ignore_for_file: constant_identifier_names
import 'package:flutter/painting.dart';

abstract final class SahelColors {
  static const brand = Color(0xFF0B4F8A);
  static const brandDark = Color(0xFF073763);
  static const brandSoft = Color(0xFFE6EFF8);
  static const accent = Color(0xFFE8A317);
  static const islamic = Color(0xFF0F7A5C);
  static const islamicSoft = Color(0xFFE3F4EE);
  static const surface = Color(0xFFFFFFFF);
  static const background = Color(0xFFF5F7FA);
  static const border = Color(0xFFDDE3EA);
  static const text = Color(0xFF0F1B2A);
  static const textMuted = Color(0xFF5B6B7F);
  static const danger = Color(0xFFC0392B);
  static const success = Color(0xFF1E8E5A);
}

abstract final class SahelRadius {
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 20;
}

abstract final class SahelSpace {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 24;
  static const double xl = 32;
}
