// Generates platform files from the shared sources so web (Next.js) and mobile (Flutter) stay in parity:
//   packages/i18n/{en,ar}.json        -> apps/mobile/lib/l10n/app_{en,ar}.arb
//   packages/design-tokens/tokens.json -> apps/web/app/tokens.css, apps/mobile/lib/core/theme/tokens.g.dart
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));
const write = (p, s) => {
  mkdirSync(dirname(join(root, p)), { recursive: true });
  writeFileSync(join(root, p), s);
  console.log('wrote', p);
};
const HEADER = 'GENERATED by tools/gen.mjs. Do not edit.';

// ---- i18n -> ARB
for (const locale of ['en', 'ar']) {
  const msgs = read(`packages/i18n/${locale}.json`);
  const arb = { '@@locale': locale, '@@x-generated': HEADER };
  for (const [key, value] of Object.entries(msgs)) {
    arb[key] = value;
    const placeholders = [...value.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
    if (locale === 'en' && placeholders.length) {
      arb[`@${key}`] = { placeholders: Object.fromEntries(placeholders.map((p) => [p, { type: 'String' }])) };
    }
  }
  write(`apps/mobile/lib/l10n/app_${locale}.arb`, JSON.stringify(arb, null, 2) + '\n');
}

// ---- tokens -> CSS + Dart
const tokens = read('packages/design-tokens/tokens.json');
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
let css = `/* ${HEADER} */\n@theme {\n`;
for (const [k, v] of Object.entries(tokens.color)) css += `  --color-${kebab(k)}: ${v};\n`;
for (const [k, v] of Object.entries(tokens.radius)) css += `  --radius-${k}: ${v}px;\n`;
css += '}\n';
write('apps/web/app/tokens.css', css);

let dart = `// ${HEADER}\n// ignore_for_file: constant_identifier_names\nimport 'package:flutter/painting.dart';\n\nabstract final class SahelColors {\n`;
for (const [k, v] of Object.entries(tokens.color)) dart += `  static const ${k} = Color(0xFF${v.slice(1).toUpperCase()});\n`;
dart += '}\n\nabstract final class SahelRadius {\n';
for (const [k, v] of Object.entries(tokens.radius)) dart += `  static const double ${k} = ${v};\n`;
dart += '}\n\nabstract final class SahelSpace {\n';
for (const [k, v] of Object.entries(tokens.space)) dart += `  static const double ${k} = ${v};\n`;
dart += '}\n';
write('apps/mobile/lib/core/theme/tokens.g.dart', dart);
